[package]
name = "redriddles"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"
enum_dispatch = "0.3"
oklab = "1.1"
rfd = "=0.16.0"
bimap = "0.6"
tuple_deref = { path = "tuple_deref" }

[features]
default = []
debug = []